// <auto-generated />
namespace Core.Ef.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Core_Ver1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Core_Ver1));
        
        string IMigrationMetadata.Id
        {
            get { return "201501150651326_Core_Ver1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
