// <auto-generated />
namespace Core.Ef.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Core_Ver3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Core_Ver3));
        
        string IMigrationMetadata.Id
        {
            get { return "201508211346085_Core_Ver3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
